-- Find what position driver Max Verstappen finished on Abu Dhabi Grand Prix 2021

SELECT * FROM 
DRIVER_STANDINGS
JOIN RACES USING(RACE_ID)
JOIN DRIVERS USING(DRIVER_ID)
WHERE NAME='Abu Dhabi Grand Prix' 
AND DRIVER_CODE = 'VER'
AND YEAR = 2021;



-- Get me the driver with most podiums in the last 10 yerars


SELECT DRIVER_ID,DRIVER_CODE, COUNT(*) AS NUMBER_PODIUMS
FROM DRIVER_STANDINGS
JOIN RACES USING(RACE_ID)
JOIN DRIVERS USING(DRIVER_ID)
WHERE POSITION <= 3
AND YEAR BETWEEN 2015 AND 2025
GROUP BY DRIVER_ID,DRIVER_CODE;

-- Get me all constructos with podiums between 2000 and 2005

SELECT constructor_ref,position,RA.name, race_date
FROM RESULTS
JOIN CONSTRUCTORS USING (CONSTRUCTOR_ID)
JOIN RACES RA USING(RACE_ID)
WHERE RA.YEAR BETWEEN 2000 AND 2005
AND POSITION <= 3
ORDER BY RACE_DATE DESC;










